### ISSUE TITLE
'Client' object has no attribute 'send_message'

### ISSUE THREAD

**Issue by thepiratebae** [EmmaSimon/sprawlbot#1]
Hi! My Sprawl group just switched to Discord and I'm hoping to get this up and running. Seems awesome! My bot appears to login successfully and shows as online, but I get the following error when I type a command. 

```
Starting sprawlbot...
Started successfully.
Use this link to invite sprawlbot to a server:
https://discordapp.com/oauth2/authorize?client_id=722937988107206686&scope=bot
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\jordan\code\sprawlbot\venv\lib\site-packages\discord\client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File ".\sprawlbot.py", line 72, in on_message
    await client.send_message(
AttributeError: 'Client' object has no attribute 'send_message'
```

I'm assuming it has something to do with permissions but I can see the bot is part of @everyone and thus has send_message privileges so I'm stumped. Using python 3.8 and installed dependencies into a venv. Any suggestions would be great! Thanks so much.

**Comment by EmmaSimon** [comment]
Ack! I should have put a version number on the pip install of discord.py, looks like they updated their API to be `client.send` instead of `client.send_message`. I can try to get a PR together, but unless there were other breaking changes from v1.0 (there don't seem to be based on a quick spot check), it should be a quick find and replace if you want to make the change then test it out and submit a PR. 😄

https://discordpy.readthedocs.io/en/latest/migrating.html#sending-messages
